
search_tweets_api:
  bearer_token: AAAAAAAAAAAAAAAAAAAAAHt2PQEAAAAAywKD%2B3JOsUGO0%2B%2FKapq7VQd%2BhOY%3DK4FRHsaZJLXZbTXsddRVY8mWU9Ym062mKyj27EgxpHP0dsOklw
azure:
  subscription_key: 2d48a627dbf549718f1f8b9eda06be6a
