
search_tweets_api:
  bearer_token: AAAAAAAAAAAAAAAAAAAAAHt2PQEAAAAAywKD%2B3JOsUGO0%2B%2FKapq7VQd%2BhOY%3DK4FRHsaZJLXZbTXsddRVY8mWU9Ym062mKyj27EgxpHP0dsOklw
azure:
  subscription_key: 7ee5dd1d-2f92-4f64-ab84-8ac420c2d089

    
